package com.tum.tummile;

import android.content.ClipData;
import android.content.ClipboardManager;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import java.util.ArrayList;

public class BengaliQuatees extends AppCompatActivity {
//bengali quatees
    ListView LV;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.bengali_quatees);

       LV = findViewById(R.id.LV);


        ArrayList<String> items = new ArrayList<>();
        items.add(getString(R.string.bengali1));
        items.add(getString(R.string.bengali2));
        items.add(getString(R.string.bengali3));
        items.add(getString(R.string.bengali4));
        items.add(getString(R.string.bengali5));
        items.add(getString(R.string.bengali6));
        items.add(getString(R.string.bengali7));
        items.add(getString(R.string.bengali8));
        items.add(getString(R.string.bengali9));
        items.add(getString(R.string.bengali10));
        items.add(getString(R.string.bengali11));
        items.add(getString(R.string.bengali12));
        items.add(getString(R.string.bengali13));
        items.add(getString(R.string.bengali14));
        items.add(getString(R.string.bengali15));
        items.add(getString(R.string.bengali16));
        items.add(getString(R.string.bengali17));
        items.add(getString(R.string.bengali18));
        items.add(getString(R.string.bengali19));
        items.add(getString(R.string.bengali20));
        items.add(getString(R.string.bengali21));
        items.add(getString(R.string.bengali22));
        items.add(getString(R.string.bengali23));
        items.add(getString(R.string.bengali24));
        items.add(getString(R.string.bengali25));
        items.add(getString(R.string.bengali26));
        items.add(getString(R.string.bengali27));
        items.add(getString(R.string.bengali28));
        items.add(getString(R.string.bengali29));
        items.add(getString(R.string.bengali30));
        items.add(getString(R.string.bengali31));
        items.add(getString(R.string.bengali32));
        items.add(getString(R.string.bengali33));
        items.add(getString(R.string.bengali34));
        items.add(getString(R.string.bengali35));
        items.add(getString(R.string.bengali36));
        items.add(getString(R.string.bengali37));
        items.add(getString(R.string.bengali38));
        items.add(getString(R.string.bengali39));
        items.add(getString(R.string.bengali40));
        items.add(getString(R.string.bengali41));
        items.add(getString(R.string.bengali42));
        items.add(getString(R.string.bengali43));
        items.add(getString(R.string.bengali44));
        items.add(getString(R.string.bengali45));
        items.add(getString(R.string.bengali46));
        items.add(getString(R.string.bengali47));
        items.add(getString(R.string.bengali48));
        items.add(getString(R.string.bengali49));
        items.add(getString(R.string.bengali50));
        items.add(getString(R.string.bengali51));
        items.add(getString(R.string.bengali52));
        items.add(getString(R.string.bengali53));
        items.add(getString(R.string.bengali54));
        items.add(getString(R.string.bengali55));
        items.add(getString(R.string.bengali56));
        items.add(getString(R.string.bengali57));
        items.add(getString(R.string.bengali58));
        items.add(getString(R.string.bengali59));
        items.add(getString(R.string.bengali60));
        items.add(getString(R.string.bengali61));
        items.add(getString(R.string.bengali62));
        items.add(getString(R.string.bengali63));
        items.add(getString(R.string.bengali64));
        items.add(getString(R.string.bengali65));
        items.add(getString(R.string.bengali66));
        items.add(getString(R.string.bengali67));
        items.add(getString(R.string.bengali68));
        items.add(getString(R.string.bengali69));
        items.add(getString(R.string.bengali70));
        items.add(getString(R.string.bengali71));
        items.add(getString(R.string.bengali72));
        items.add(getString(R.string.bengali73));
        items.add(getString(R.string.bengali74));
        items.add(getString(R.string.bengali75));
        items.add(getString(R.string.bengali76));
        items.add(getString(R.string.bengali77));
        items.add(getString(R.string.bengali78));
        items.add(getString(R.string.bengali79));
        items.add(getString(R.string.bengali80));
        items.add(getString(R.string.bengali81));
        items.add(getString(R.string.bengali82));
        items.add(getString(R.string.bengali83));
        items.add(getString(R.string.bengali84));
        items.add(getString(R.string.bengali85));
        items.add(getString(R.string.bengali86));
        items.add(getString(R.string.bengali87));
        items.add(getString(R.string.bengali88));
        items.add(getString(R.string.bengali89));
        items.add(getString(R.string.bengali90));
        items.add(getString(R.string.bengali91));
        items.add(getString(R.string.bengali92));
        items.add(getString(R.string.bengali93));
        items.add(getString(R.string.bengali94));
        items.add(getString(R.string.bengali95));
        items.add(getString(R.string.bengali96));
        items.add(getString(R.string.bengali97));
        items.add(getString(R.string.bengali98));
        items.add(getString(R.string.bengali99));
        items.add(getString(R.string.bengali100));
        items.add(getString(R.string.bengali101));
        items.add(getString(R.string.bengali102));
        items.add(getString(R.string.bengali103));
        items.add(getString(R.string.bengali104));
        items.add(getString(R.string.bengali105));
        items.add(getString(R.string.bengali106));
        items.add(getString(R.string.bengali107));
        items.add(getString(R.string.bengali108));
        items.add(getString(R.string.bengali109));
        items.add(getString(R.string.bengali110));
        items.add(getString(R.string.bengali111));
        items.add(getString(R.string.bengali112));
        items.add(getString(R.string.bengali113));
        items.add(getString(R.string.bengali114));
        items.add(getString(R.string.bengali115));
        items.add(getString(R.string.bengali116));
        items.add(getString(R.string.bengali117));
        items.add(getString(R.string.bengali118));
        items.add(getString(R.string.bengali119));
        items.add(getString(R.string.bengali120));
        items.add(getString(R.string.bengali121));
        items.add(getString(R.string.bengali122));
        items.add(getString(R.string.bengali123));
        items.add(getString(R.string.bengali124));
        items.add(getString(R.string.bengali125));
        items.add(getString(R.string.bengali126));
        items.add(getString(R.string.bengali127));
        items.add(getString(R.string.bengali128));
        items.add(getString(R.string.bengali129));
        items.add(getString(R.string.bengali130));
        items.add(getString(R.string.bengali131));
        items.add(getString(R.string.bengali132));
        items.add(getString(R.string.bengali133));
        items.add(getString(R.string.bengali134));
        items.add(getString(R.string.bengali135));
        items.add(getString(R.string.bengali136));
        items.add(getString(R.string.bengali137));
        items.add(getString(R.string.bengali138));
        items.add(getString(R.string.bengali139));
        items.add(getString(R.string.bengali140));
        items.add(getString(R.string.bengali141));
        items.add(getString(R.string.bengali142));
        items.add(getString(R.string.bengali143));
        items.add(getString(R.string.bengali144));
        items.add(getString(R.string.bengali145));
        items.add(getString(R.string.bengali146));
        items.add(getString(R.string.bengali147));
        items.add(getString(R.string.bengali148));
        items.add(getString(R.string.bengali149));
        items.add(getString(R.string.bengali150));
        items.add(getString(R.string.bengali151));
        items.add(getString(R.string.bengali152));
        items.add(getString(R.string.bengali153));
        items.add(getString(R.string.bengali154));
        items.add(getString(R.string.bengali155));
        items.add(getString(R.string.bengali156));
        items.add(getString(R.string.bengali157));
        items.add(getString(R.string.bengali158));
        items.add(getString(R.string.bengali159));
        items.add(getString(R.string.bengali160));
        items.add(getString(R.string.bengali161));
        items.add(getString(R.string.bengali162));
        items.add(getString(R.string.bengali163));
        items.add(getString(R.string.bengali164));
        items.add(getString(R.string.bengali165));
        items.add(getString(R.string.bengali166));
        items.add(getString(R.string.bengali167));
        items.add(getString(R.string.bengali168));
        items.add(getString(R.string.bengali169));
        items.add(getString(R.string.bengali170));
        items.add(getString(R.string.bengali171));
        items.add(getString(R.string.bengali172));
        items.add(getString(R.string.bengali173));
        items.add(getString(R.string.bengali174));
        items.add(getString(R.string.bengali175));
        items.add(getString(R.string.bengali176));
        items.add(getString(R.string.bengali177));
        items.add(getString(R.string.bengali178));
        items.add(getString(R.string.bengali179));
        items.add(getString(R.string.bengali180));
        items.add(getString(R.string.bengali181));
        items.add(getString(R.string.bengali182));
        items.add(getString(R.string.bengali183));
        items.add(getString(R.string.bengali184));
        items.add(getString(R.string.bengali185));
        items.add(getString(R.string.bengali186));
        items.add(getString(R.string.bengali187));
        items.add(getString(R.string.bengali188));
        items.add(getString(R.string.bengali189));
        items.add(getString(R.string.bengali190));
        items.add(getString(R.string.bengali191));
        items.add(getString(R.string.bengali192));
        items.add(getString(R.string.bengali193));
        items.add(getString(R.string.bengali194));
        items.add(getString(R.string.bengali195));
        items.add(getString(R.string.bengali196));
        items.add(getString(R.string.bengali197));
        items.add(getString(R.string.bengali198));
        items.add(getString(R.string.bengali199));
        items.add(getString(R.string.bengali200));
        items.add(getString(R.string.bengali201));
        items.add(getString(R.string.bengali202));
     items.add(getString(R.string.bengali203));
     items.add(getString(R.string.bengali204));
     items.add(getString(R.string.bengali205));
     items.add(getString(R.string.bengali206));
     items.add(getString(R.string.bengali207));
     items.add(getString(R.string.bengali208));
     items.add(getString(R.string.bengali209));
     items.add(getString(R.string.bengali210));
     items.add(getString(R.string.bengali211));
     items.add(getString(R.string.bengali212));
     items.add(getString(R.string.bengali213));
     items.add(getString(R.string.bengali214));
     items.add(getString(R.string.bengali215));
     items.add(getString(R.string.bengali216));
     items.add(getString(R.string.bengali217));
     items.add(getString(R.string.bengali218));
     items.add(getString(R.string.bengali219));
     items.add(getString(R.string.bengali220));
     items.add(getString(R.string.bengali221));
     items.add(getString(R.string.bengali222));
     items.add(getString(R.string.bengali223));
     items.add(getString(R.string.bengali224));
     items.add(getString(R.string.bengali225));
     items.add(getString(R.string.bengali226));
     items.add(getString(R.string.bengali227));
     items.add(getString(R.string.bengali228));
     items.add(getString(R.string.bengali229));
     items.add(getString(R.string.bengali230));
     items.add(getString(R.string.bengali231));
     items.add(getString(R.string.bengali232));
     items.add(getString(R.string.bengali233));
     items.add(getString(R.string.bengali234));
     items.add(getString(R.string.bengali235));
     items.add(getString(R.string.bengali236));
     items.add(getString(R.string.bengali237));
     items.add(getString(R.string.bengali238));
     items.add(getString(R.string.bengali239));
     items.add(getString(R.string.bengali240));
     items.add(getString(R.string.bengali241));
     items.add(getString(R.string.bengali242));
     items.add(getString(R.string.bengali243));
     items.add(getString(R.string.bengali244));
     items.add(getString(R.string.bengali245));
     items.add(getString(R.string.bengali246));
     items.add(getString(R.string.bengali247));
     items.add(getString(R.string.bengali248));
     items.add(getString(R.string.bengali249));
     items.add(getString(R.string.bengali250));
     items.add(getString(R.string.bengali251));
     items.add(getString(R.string.bengali252));
     items.add(getString(R.string.bengali253));
     items.add(getString(R.string.bengali254));
     items.add(getString(R.string.bengali255));
     items.add(getString(R.string.bengali256));
     items.add(getString(R.string.bengali257));
     items.add(getString(R.string.bengali258));
     items.add(getString(R.string.bengali259));
     items.add(getString(R.string.bengali260));
     items.add(getString(R.string.bengali261));
     items.add(getString(R.string.bengali262));
     items.add(getString(R.string.bengali263));
     items.add(getString(R.string.bengali264));
     items.add(getString(R.string.bengali265));
     items.add(getString(R.string.bengali266));
     items.add(getString(R.string.bengali267));
     items.add(getString(R.string.bengali268));
     items.add(getString(R.string.bengali269));
     items.add(getString(R.string.bengali270));
     items.add(getString(R.string.bengali271));
     items.add(getString(R.string.bengali272));
     items.add(getString(R.string.bengali273));
     items.add(getString(R.string.bengali274));
     items.add(getString(R.string.bengali275));
     items.add(getString(R.string.bengali276));
     items.add(getString(R.string.bengali277));
     items.add(getString(R.string.bengali278));
     items.add(getString(R.string.bengali279));
     items.add(getString(R.string.bengali280));
     items.add(getString(R.string.bengali281));
     items.add(getString(R.string.bengali282));
     items.add(getString(R.string.bengali283));
     items.add(getString(R.string.bengali284));
     items.add(getString(R.string.bengali285));
     items.add(getString(R.string.bengali286));
     items.add(getString(R.string.bengali287));
     items.add(getString(R.string.bengali288));
     items.add(getString(R.string.bengali289));
     items.add(getString(R.string.bengali290));
     items.add(getString(R.string.bengali291));
     items.add(getString(R.string.bengali292));
     items.add(getString(R.string.bengali293));
     items.add(getString(R.string.bengali294));
     items.add(getString(R.string.bengali295));
     items.add(getString(R.string.bengali296));
     items.add(getString(R.string.bengali297));
     items.add(getString(R.string.bengali298));
     items.add(getString(R.string.bengali299));
     items.add(getString(R.string.bengali300));



     ArrayAdapter<String> pushItems = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1,items);
        LV.setAdapter(pushItems);


        // Set an item click listener
        LV.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Get the text of the clicked item
                String textToCopy = items.get(position);
                // Get the ClipboardManager system service
                ClipboardManager clipboard = (ClipboardManager) getSystemService(CLIPBOARD_SERVICE);
                // Create ClipData with the text to copy
                ClipData clip = ClipData.newPlainText("text", textToCopy);
                // Set the clipboard data share send to device
                clipboard.setPrimaryClip(clip);
                // Provide feedback to the user
                Toast.makeText(BengaliQuatees.this, "Copied" + textToCopy, Toast.LENGTH_SHORT).show();
            }
        });
    }
}




