package com.tum.tummile;

import android.content.ClipData;
import android.content.ClipboardManager;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.Random;

// Hindi quateees.............
public class HindiQuatees extends AppCompatActivity{
    ListView LV;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.hindi_quatees);

        LV = findViewById(R.id.LV);


        ArrayList<String> items = new ArrayList<>();
        items.add(getString(R.string.hindi1));
        items.add(getString(R.string.hindi2));
        items.add(getString(R.string.hindi3));
        items.add(getString(R.string.hindi4));
        items.add(getString(R.string.hindi5));
        items.add(getString(R.string.hindi6));
        items.add(getString(R.string.hindi7));
        items.add(getString(R.string.hindi8));
        items.add(getString(R.string.hindi9));
        items.add(getString(R.string.hindi10));
        items.add(getString(R.string.hindi11));
        items.add(getString(R.string.hindi12));
        items.add(getString(R.string.hindi13));
        items.add(getString(R.string.hindi14));
        items.add(getString(R.string.hindi15));
        items.add(getString(R.string.hindi16));
        items.add(getString(R.string.hindi17));
        items.add(getString(R.string.hindi18));
        items.add(getString(R.string.hindi19));
        items.add(getString(R.string.hindi20));
        items.add(getString(R.string.hindi21));
        items.add(getString(R.string.hindi22));
        items.add(getString(R.string.hindi23));
        items.add(getString(R.string.hindi24));
        items.add(getString(R.string.hindi25));
        items.add(getString(R.string.hindi26));
        items.add(getString(R.string.hindi27));
        items.add(getString(R.string.hindi28));
        items.add(getString(R.string.hindi29));
        items.add(getString(R.string.hindi30));
        items.add(getString(R.string.hindi31));
        items.add(getString(R.string.hindi32));
        items.add(getString(R.string.hindi33));
        items.add(getString(R.string.hindi34));
        items.add(getString(R.string.hindi35));
        items.add(getString(R.string.hindi36));
        items.add(getString(R.string.hindi37));
        items.add(getString(R.string.hindi38));
        items.add(getString(R.string.hindi39));
        items.add(getString(R.string.hindi40));
        items.add(getString(R.string.hindi41));
        items.add(getString(R.string.hindi42));
        items.add(getString(R.string.hindi43));
        items.add(getString(R.string.hindi44));
        items.add(getString(R.string.hindi45));
        items.add(getString(R.string.hindi46));
        items.add(getString(R.string.hindi47));
        items.add(getString(R.string.hindi48));
        items.add(getString(R.string.hindi49));
        items.add(getString(R.string.hindi50));
        items.add(getString(R.string.hindi51));
        items.add(getString(R.string.hindi52));
        items.add(getString(R.string.hindi53));
        items.add(getString(R.string.hindi54));
        items.add(getString(R.string.hindi55));
        items.add(getString(R.string.hindi56));
        items.add(getString(R.string.hindi57));
        items.add(getString(R.string.hindi58));
        items.add(getString(R.string.hindi59));
        items.add(getString(R.string.hindi60));
        items.add(getString(R.string.hindi61));
        items.add(getString(R.string.hindi62));
        items.add(getString(R.string.hindi63));
        items.add(getString(R.string.hindi64));
        items.add(getString(R.string.hindi65));
        items.add(getString(R.string.hindi66));
        items.add(getString(R.string.hindi67));
        items.add(getString(R.string.hindi68));
        items.add(getString(R.string.hindi69));
        items.add(getString(R.string.hindi70));
        items.add(getString(R.string.hindi71));
        items.add(getString(R.string.hindi72));
        items.add(getString(R.string.hindi73));
        items.add(getString(R.string.hindi74));
        items.add(getString(R.string.hindi75));
        items.add(getString(R.string.hindi76));
        items.add(getString(R.string.hindi77));
        items.add(getString(R.string.hindi78));
        items.add(getString(R.string.hindi79));
        items.add(getString(R.string.hindi80));
        items.add(getString(R.string.hindi81));
        items.add(getString(R.string.hindi82));
        items.add(getString(R.string.hindi83));
        items.add(getString(R.string.hindi84));
        items.add(getString(R.string.hindi85));
        items.add(getString(R.string.hindi86));
        items.add(getString(R.string.hindi87));
        items.add(getString(R.string.hindi88));
        items.add(getString(R.string.hindi89));
        items.add(getString(R.string.hindi90));
        items.add(getString(R.string.hindi91));
        items.add(getString(R.string.hindi92));
        items.add(getString(R.string.hindi93));
        items.add(getString(R.string.hindi4));
        items.add(getString(R.string.hindi95));
        items.add(getString(R.string.hindi96));
        items.add(getString(R.string.hindi97));
        items.add(getString(R.string.hindi98));
        items.add(getString(R.string.hindi99));
        items.add(getString(R.string.hindi100));
        items.add(getString(R.string.hindi101));
        items.add(getString(R.string.hindi102));
        items.add(getString(R.string.hindi103));
        items.add(getString(R.string.hindi104));
        items.add(getString(R.string.hindi105));
        items.add(getString(R.string.hindi106));
        items.add(getString(R.string.hindi107));
        items.add(getString(R.string.hindi108));
        items.add(getString(R.string.hindi109));
        items.add(getString(R.string.hindi110));
        items.add(getString(R.string.hindi111));
        items.add(getString(R.string.hindi112));
        items.add(getString(R.string.hindi113));
        items.add(getString(R.string.hindi114));
        items.add(getString(R.string.hindi115));
        items.add(getString(R.string.hindi116));
        items.add(getString(R.string.hindi117));
        items.add(getString(R.string.hindi118));
        items.add(getString(R.string.hindi119));
        items.add(getString(R.string.hindi120));
        items.add(getString(R.string.hindi121));
        items.add(getString(R.string.hindi122));
        items.add(getString(R.string.hindi123));
        items.add(getString(R.string.hindi124));
        items.add(getString(R.string.hindi125));
        items.add(getString(R.string.hindi126));
        items.add(getString(R.string.hindi127));
        items.add(getString(R.string.hindi128));
        items.add(getString(R.string.hindi129));
        items.add(getString(R.string.hindi130));
        items.add(getString(R.string.hindi131));
        items.add(getString(R.string.hindi132));
        items.add(getString(R.string.hindi133));
        items.add(getString(R.string.hindi134));
        items.add(getString(R.string.hindi135));
        items.add(getString(R.string.hindi136));
        items.add(getString(R.string.hindi137));
        items.add(getString(R.string.hindi138));
        items.add(getString(R.string.hindi139));
        items.add(getString(R.string.hindi140));
        items.add(getString(R.string.hindi141));
        items.add(getString(R.string.hindi142));
        items.add(getString(R.string.hindi143));
        items.add(getString(R.string.hindi144));
        items.add(getString(R.string.hindi145));
        items.add(getString(R.string.hindi146));
        items.add(getString(R.string.hindi147));
        items.add(getString(R.string.hindi148));
        items.add(getString(R.string.hindi149));
        items.add(getString(R.string.hindi150));
        items.add(getString(R.string.hindi151));
        items.add(getString(R.string.hindi152));
        items.add(getString(R.string.hindi153));
        items.add(getString(R.string.hindi154));
        items.add(getString(R.string.hindi155));
        items.add(getString(R.string.hindi156));
        items.add(getString(R.string.hindi157));
        items.add(getString(R.string.hindi158));
        items.add(getString(R.string.hindi159));
        items.add(getString(R.string.hindi160));
        items.add(getString(R.string.hindi161));
        items.add(getString(R.string.hindi162));
        items.add(getString(R.string.hindi163));
        items.add(getString(R.string.hindi164));
        items.add(getString(R.string.hindi165));
        items.add(getString(R.string.hindi166));
        items.add(getString(R.string.hindi167));
        items.add(getString(R.string.hindi168));
        items.add(getString(R.string.hindi169));
        items.add(getString(R.string.hindi170));
        items.add(getString(R.string.hindi171));
        items.add(getString(R.string.hindi172));
        items.add(getString(R.string.hindi173));
        items.add(getString(R.string.hindi174));
        items.add(getString(R.string.hindi175));
        items.add(getString(R.string.hindi176));
        items.add(getString(R.string.hindi177));
        items.add(getString(R.string.hindi178));
        items.add(getString(R.string.hindi179));
        items.add(getString(R.string.hindi180));
        items.add(getString(R.string.hindi181));
        items.add(getString(R.string.hindi182));
        items.add(getString(R.string.hindi183));
        items.add(getString(R.string.hindi184));
        items.add(getString(R.string.hindi185));
        items.add(getString(R.string.hindi186));
        items.add(getString(R.string.hindi187));
        items.add(getString(R.string.hindi188));
        items.add(getString(R.string.hindi189));
        items.add(getString(R.string.hindi190));
        items.add(getString(R.string.hindi191));
        items.add(getString(R.string.hindi192));
        items.add(getString(R.string.hindi193));
        items.add(getString(R.string.hindi194));
        items.add(getString(R.string.hindi195));
        items.add(getString(R.string.hindi196));
        items.add(getString(R.string.hindi197));
        items.add(getString(R.string.hindi198));
        items.add(getString(R.string.hindi199));
        items.add(getString(R.string.hindi200));
        items.add(getString(R.string.hindi201));
        items.add(getString(R.string.hindi202));
        items.add(getString(R.string.hindi203));
        items.add(getString(R.string.hindi204));
        items.add(getString(R.string.hindi205));
        items.add(getString(R.string.hindi206));
        items.add(getString(R.string.hindi207));
        items.add(getString(R.string.hindi208));
        items.add(getString(R.string.hindi209));
        items.add(getString(R.string.hindi210));
        items.add(getString(R.string.hindi211));
        items.add(getString(R.string.hindi212));
        items.add(getString(R.string.hindi213));
        items.add(getString(R.string.hindi214));
        items.add(getString(R.string.hindi215));
        items.add(getString(R.string.hindi216));
        items.add(getString(R.string.hindi217));
        items.add(getString(R.string.hindi218));
        items.add(getString(R.string.hindi219));
        items.add(getString(R.string.hindi220));
        items.add(getString(R.string.hindi221));
        items.add(getString(R.string.hindi222));
        items.add(getString(R.string.hindi223));
        items.add(getString(R.string.hindi224));
        items.add(getString(R.string.hindi225));
        items.add(getString(R.string.hindi226));
        items.add(getString(R.string.hindi227));
        items.add(getString(R.string.hindi228));
        items.add(getString(R.string.hindi229));
        items.add(getString(R.string.hindi230));
        items.add(getString(R.string.hindi231));
        items.add(getString(R.string.hindi232));
        items.add(getString(R.string.hindi233));
        items.add(getString(R.string.hindi234));
        items.add(getString(R.string.hindi235));
        items.add(getString(R.string.hindi236));
        items.add(getString(R.string.hindi237));
        items.add(getString(R.string.hindi238));
        items.add(getString(R.string.hindi239));
        items.add(getString(R.string.hindi240));
        items.add(getString(R.string.hindi241));
        items.add(getString(R.string.hindi242));
        items.add(getString(R.string.hindi243));
        items.add(getString(R.string.hindi244));
        items.add(getString(R.string.hindi245));
        items.add(getString(R.string.hindi246));
        items.add(getString(R.string.hindi247));
        items.add(getString(R.string.hindi248));
        items.add(getString(R.string.hindi249));
        items.add(getString(R.string.hindi250));
        items.add(getString(R.string.hindi251));
        items.add(getString(R.string.hindi252));
        items.add(getString(R.string.hindi253));
        items.add(getString(R.string.hindi254));
        items.add(getString(R.string.hindi255));
        items.add(getString(R.string.hindi256));
        items.add(getString(R.string.hindi257));
        items.add(getString(R.string.hindi258));
        items.add(getString(R.string.hindi259));
        items.add(getString(R.string.hindi260));
        items.add(getString(R.string.hindi261));
        items.add(getString(R.string.hindi262));
        items.add(getString(R.string.hindi263));
        items.add(getString(R.string.hindi264));
        items.add(getString(R.string.hindi265));
        items.add(getString(R.string.hindi266));
        items.add(getString(R.string.hindi267));
        items.add(getString(R.string.hindi268));
        items.add(getString(R.string.hindi269));
        items.add(getString(R.string.hindi270));
        items.add(getString(R.string.hindi271));
        items.add(getString(R.string.hindi272));
        items.add(getString(R.string.hindi273));
        items.add(getString(R.string.hindi274));
        items.add(getString(R.string.hindi275));
        items.add(getString(R.string.hindi276));
        items.add(getString(R.string.hindi277));
        items.add(getString(R.string.hindi278));
        items.add(getString(R.string.hindi279));
        items.add(getString(R.string.hindi280));
        items.add(getString(R.string.hindi281));
        items.add(getString(R.string.hindi282));
        items.add(getString(R.string.hindi283));
        items.add(getString(R.string.hindi284));
        items.add(getString(R.string.hindi285));
        items.add(getString(R.string.hindi286));
        items.add(getString(R.string.hindi287));
        items.add(getString(R.string.hindi288));
        items.add(getString(R.string.hindi289));
        items.add(getString(R.string.hindi290));
        items.add(getString(R.string.hindi291));
        items.add(getString(R.string.hindi292));
        items.add(getString(R.string.hindi293));
        items.add(getString(R.string.hindi294));
        items.add(getString(R.string.hindi295));
        items.add(getString(R.string.hindi296));
        items.add(getString(R.string.hindi297));
        items.add(getString(R.string.hindi298));
        items.add(getString(R.string.hindi299));
        items.add(getString(R.string.hindi300));



                ArrayAdapter<String> pushItems = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1,items);
        LV.setAdapter(pushItems);


        // Set an item click listener
        LV.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                // Get the text of the clicked item
                String textToCopy = items.get(position);
                // Get the ClipboardManager system service
                ClipboardManager clipboard = (ClipboardManager) getSystemService(CLIPBOARD_SERVICE);
                // Create ClipData with the text to copy
                ClipData clip = ClipData.newPlainText("text", textToCopy);
                // Set the clipboard data share send to device
                clipboard.setPrimaryClip(clip);
                // Provide feedback to the user
                Toast.makeText(HindiQuatees.this, "Copied" + textToCopy, Toast.LENGTH_SHORT).show();
            }
        });
    }
}